# Ensemble methods. Exercises


In this section we have only two exercise:

1. Find the best three classifier in the stacking method using the classifiers from scikit-learn package.

2. Build arcing arc-x4 method. 

In [1]:
%store -r data_set
%store -r labels
%store -r test_data_set
%store -r test_labels
%store -r unique_labels

print("data_set", data_set)
print("labels", labels)
print("test_data_set", test_data_set)
print("test_labels", test_labels)
print("unique_labels", unique_labels)

data_set [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

## Exercise 1: Find the best three classifier in the stacking method

Please use the following classifiers:

* Linear regression,
* Nearest Neighbors,
* Linear SVM,
* Decision Tree,
* Naive Bayes,
* QDA.

In [36]:
import numpy as np
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from itertools import combinations

In [37]:
def build_classifiers():
    classifiers = [
        LogisticRegression(max_iter=1000),
        KNeighborsClassifier(),
        SVC(kernel='linear'),
        DecisionTreeClassifier(),
        GaussianNB(),
        QuadraticDiscriminantAnalysis()
    ]
    return classifiers

In [38]:
def build_stacked_classifier(classifiers):
    output = []
    for classifier in classifiers:
        output.append(classifier.predict(data_set))
    output = np.array(output).reshape((130,3))
    
    stacked_classifier = LogisticRegression()
    stacked_classifier.fit(output.reshape((130,3)), labels.reshape((130,)))
    test_set = []
    for classifier in classifiers:
        test_set.append(classifier.predict(test_data_set))
    test_set = np.array(test_set).reshape((len(test_set[0]),3))
    predicted = stacked_classifier.predict(test_set)
    return predicted

In [39]:
classifiers = build_classifiers()
for classifier in classifiers:
    classifier.fit(data_set, labels)

# Trying all combinations of 3 classifiers and selecting the best one
best_accuracy = 0
best_combination = None
for comb in combinations(classifiers, 3):
    predicted = build_stacked_classifier(comb)
    accuracy = accuracy_score(test_labels, predicted)
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_combination = comb

    print(f"{accuracy:.2f}", end=" ")
    for c in comb:
        print(type(c).__name__, end=" ")
    print()

print("\nBest combination:")
print(f"{best_accuracy:.2f}", end=" ")
for c in best_combination:
    print(type(c).__name__, end=" ")

0.90 LogisticRegression KNeighborsClassifier SVC 
0.90 LogisticRegression KNeighborsClassifier DecisionTreeClassifier 
0.90 LogisticRegression KNeighborsClassifier GaussianNB 
0.90 LogisticRegression KNeighborsClassifier QuadraticDiscriminantAnalysis 
0.80 LogisticRegression SVC DecisionTreeClassifier 
0.80 LogisticRegression SVC GaussianNB 
0.90 LogisticRegression SVC QuadraticDiscriminantAnalysis 
0.80 LogisticRegression DecisionTreeClassifier GaussianNB 
0.90 LogisticRegression DecisionTreeClassifier QuadraticDiscriminantAnalysis 
0.95 LogisticRegression GaussianNB QuadraticDiscriminantAnalysis 
0.85 KNeighborsClassifier SVC DecisionTreeClassifier 
0.85 KNeighborsClassifier SVC GaussianNB 
0.90 KNeighborsClassifier SVC QuadraticDiscriminantAnalysis 
0.85 KNeighborsClassifier DecisionTreeClassifier GaussianNB 
0.90 KNeighborsClassifier DecisionTreeClassifier QuadraticDiscriminantAnalysis 
0.95 KNeighborsClassifier GaussianNB QuadraticDiscriminantAnalysis 
0.80 SVC DecisionTreeClassif

## Exercise 2: 

Use the boosting method and change the code to fullfilt the following requirements:

* the weights should be calculated as:
$w_{n}^{(t+1)}=\frac{1+ I(y_{n}\neq h_{t}(x_{n})}{\sum_{i=1}^{N}1+I(y_{n}\neq h_{t}(x_{n})}$,
* the prediction is done with a voting method.

In [176]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# prepare data set
def generate_data(sample_number, feature_number, label_number):
    data_set = np.random.random_sample((sample_number, feature_number))
    labels = np.random.choice(label_number, sample_number)
    return data_set, labels

labels = 2
dimension = 2
test_set_size = 1000
train_set_size = 5000
train_set, train_labels = generate_data(train_set_size, dimension, labels)
test_set, test_labels = generate_data(test_set_size, dimension, labels)

# init weights
number_of_iterations = 10
weights = np.ones((test_set_size,)) / test_set_size

def train_model(classifier, weights):
    return classifier.fit(X=test_set, y=test_labels, sample_weight=weights)

def calculate_accuracy_vector(predicted, test_labels):
    return np.array([int(x != y) for x, y in zip(predicted, test_labels)])

def calculate_error(model):
    predicted = model.predict(test_set)
    I = calculate_accuracy_vector(predicted, test_labels)
    Z = np.sum(I)
    return (1 + Z) / 1.0

Fill the two functions below:

In [177]:
def set_new_weights(model):
    predicted = model.predict(test_set)
    accuracy_vector = calculate_accuracy_vector(predicted, test_labels)
    new_weights = (accuracy_vector + 1) / np.sum(accuracy_vector + 1)
    return new_weights

Train the classifier with the code below:

In [178]:
classifier = DecisionTreeClassifier(max_depth=1, random_state=1)
classifier.fit(X=train_set, y=train_labels)
alphas = []
classifiers = []

for iteration in range(number_of_iterations):
    model = train_model(classifier, weights)
    weights = set_new_weights(model)
    alphas.append(weights)
    classifiers.append(model)

Set the validation data set:

In [179]:
validate_x, validate_label = generate_data(1, dimension, labels)
print(validate_x, validate_label)

[[0.05564648 0.00038816]] [1]


Fill the prediction code:

In [180]:
def get_prediction(classifiers, alphas, data):
    predictions = np.array([classifier.predict(data) for classifier in classifiers])
    weighted_votes = np.zeros((data.shape[0], labels))

    for alpha, classifier in zip(alphas, classifiers):
        class_predictions = classifier.predict(data).astype(int)
        for i in range(data.shape[0]):
            weighted_votes[i, class_predictions[i]] += alpha[i]

    return np.argmax(weighted_votes, axis=1)

Test it:

In [181]:
validate_x, validate_label = generate_data(1, dimension, labels)
prediction = get_prediction(classifiers, alphas, validate_x)
print("Prediction for validation data:", prediction)


Prediction for validation data: [1]
